package leetcode_easy;

//	t는 s문자열을 기반으로 랜덤으로 추가 된 문자가 있는 문자열, 추가 된 문자가 무엇인지 찾아 반환
//	모든 문자는 소문자로 가정
//	Given two strings s and t which consist of only lowercase letters.
//	String t is generated by random shuffling string s and then add one more letter at a random position.
//	Find the letter that was added in t.

public class FindDifference {

	public static char findTheDifference(String s, String t) {
        
		int alphabet[] = new int[26];
		for(int i=0; i<s.length(); i++) {
			alphabet[s.charAt(i) - 'a'] += 1;
		}
		
		for(int j=0; j<t.length(); j++) {
			alphabet[t.charAt(j) - 'a'] -= 1;
		}
		
		for(int k=0; k<alphabet.length; k++) {
			if(alphabet[k] != 0) {
				
				return (char) (k + 'a');
			}
		}
		return 0;
		
		
//		다른 문풀
//		t는 s에서 한 문자가 더 해진 문자열이므로, 
//		각각 문자열을 모두 합한 값에서 서로 빼주면 추가된 알파벳의 아스키코드를 알 수 있음! 
//		int charS = 0;
//		int charT = (int)t.charAt(t.length()-1);
//		for(int i=0; i<s.length(); i++) {
//			charS += (int)s.charAt(i);
//			charT += (int)t.charAt(i);
//		}
//		
//		return (char) (charT - charS);
    }
	
	public static void main(String[] args) {
		
		String s = "abcd";
		String t = "abcde";
		System.out.println(findTheDifference(s, t));
	}
	
}
